### ISSUE TITLE
Error sending photo: [400]

### ISSUE THREAD

**Issue by jpalenz77** [StackTraceYo/plex-bot#25]
Hello I just installed the ombi-bot 2.0 in docker on ubuntu 18.04 and while /tvserach works as expected, /moviesearch doesnt returning:

```21:43:40.508 [servername_requests Telegram Executor] DEBUG org.stacktrace.yo.plexbot.bots.ombi.OmbiCallbackHandler - Replying with Available in Plex


org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending photo: [400] Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard


	at org.telegram.telegrambots.meta.api.methods.send.SendPhoto.deserializeResponse(SendPhoto.java:146)


	at org.telegram.telegrambots.bots.DefaultAbsSender.execute(DefaultAbsSender.java:226)


	at org.stacktrace.yo.plexbot.bots.ombi.OmbiCallbackHandler.sendPhoto(OmbiCallbackHandler.java:271)


	at org.stacktrace.yo.plexbot.bots.ombi.OmbiCallbackHandler.doReply(OmbiCallbackHandler.java:69)


	at org.stacktrace.yo.plexbot.bots.ombi.OmbiCommand.execute(OmbiCommand.java:38)


	at org.telegram.telegrambots.extensions.bots.commandbot.commands.BotCommand.processMessage(BotCommand.java:78)


	at org.telegram.telegrambots.extensions.bots.commandbot.commands.CommandRegistry.executeCommand(CommandRegistry.java:106)


	at org.telegram.telegrambots.extensions.bots.commandbot.TelegramLongPollingCommandBot.onUpdateReceived(TelegramLongPollingCommandBot.java:69)


	at java.util.ArrayList.forEach(ArrayList.java:1257)


	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)


	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:305)```

**Comment by StackTraceYo** [comment]
Those look like logs for 1.x

**Comment by StackTraceYo** [comment]
Looks like the latest tag doesn’t have 2.0

**Comment by StackTraceYo** [comment]
I pushed the image again as latest. can you try again. whats the search string you are using?

**Comment by jpalenz77** [comment]
I am using :latest

**Comment by jpalenz77** [comment]
and for movies I am using `/searchmovie the movie`

**Comment by StackTraceYo** [comment]
> I am using :latest

I repushed the new latest. for some reason it wasnt updated correctly. can you repull and try again?

**Comment by jpalenz77** [comment]
sure, one second

**Comment by jpalenz77** [comment]
now I get this even though the `BOT_TOKEN`is there

```Exception in thread "main" java.lang.IllegalArgumentException: ENV file is missing Missing BOT_TOKEN


	at org.stacktrace.yo.ombi.ConfigLoader$.$anonfun$apply$8(OmbiBot.scala:390)


	at scala.collection.MapLike.getOrElse(MapLike.scala:127)


	at scala.collection.MapLike.getOrElse$(MapLike.scala:125)


	at scala.collection.AbstractMap.getOrElse(Map.scala:59)


	at org.stacktrace.yo.ombi.ConfigLoader$.apply(OmbiBot.scala:390)


	at org.stacktrace.yo.ombi.OmbiBotRunner$.delayedEndpoint$org$stacktrace$yo$ombi$OmbiBotRunner$1(OmbiBot.scala:346)


	at org.stacktrace.yo.ombi.OmbiBotRunner$delayedInit$body.apply(OmbiBot.scala:344)


	at scala.Function0.apply$mcV$sp(Function0.scala:34)


	at scala.Function0.apply$mcV$sp$(Function0.scala:34)


	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)


	at scala.App.$anonfun$main$1$adapted(App.scala:76)


	at scala.collection.immutable.List.foreach(List.scala:388)


	at scala.App.main(App.scala:76)


	at scala.App.main$(App.scala:74)


	at org.stacktrace.yo.ombi.OmbiBotRunner$.main(OmbiBot.scala:344)


	at org.stacktrace.yo.ombi.OmbiBotRunner.main(OmbiBot.scala)```

**Comment by jpalenz77** [comment]
`Exception in thread "main" java.lang.IllegalArgumentException: ENV file is missing Missing BOT_TOKEN`

**Comment by StackTraceYo** [comment]
> `Exception in thread "main" java.lang.IllegalArgumentException: ENV file is missing Missing BOT_TOKEN`

how are you executing the docker run command

**Comment by jpalenz77** [comment]
`docker run -d --name="ombibot" --net="Plexus" -e PGID=1000 -e PUID=1000 --env-file bot.env -v /docker/ombibot/bot.env:/bot.env --restart always -d stacktraceyo/ombi-bot:latest `

**Comment by jpalenz77** [comment]
but like this I am getting the same error:
(EDITED FOR PRIVACY REASONS)

`docker run -d --name="ombibot" --net="Plexus" -e PGID=1000 -e PUID=1000 -e "OMBI_HOST=http://10.0.0.16:3579/ombi" -e "OMBI_KEY=key" -e "OMBI_BOT_TOKEN=token" -e "OMBI_BOT_NAME=name" -e "OMBI_USER_NAME=user" --restart always stacktraceyo/ombi-bot:latest`

**Comment by jpalenz77** [comment]
and before you repushed the image it was working with the same command but only for tvshows

**Comment by StackTraceYo** [comment]
attempting to reproduce.

**Comment by jpalenz77** [comment]
![Captura de pantalla 2020-04-26 a las 0 39 45](https://user-images.githubusercontent.com/52360505/80292358-89f9ad00-8756-11ea-8399-500caff4d6b6.png)

**Comment by StackTraceYo** [comment]
I changed the env variable from OMBI_BOT_TOKEN TO BOT_TOKEN AND OMBI_BOT_NAME TO BOT_NAME.

thats my mistake homie.

**Comment by StackTraceYo** [comment]
ill make the change to look for either now.

**Comment by jpalenz77** [comment]
That is great, let me know when I can repull the image, thanks!

**Comment by StackTraceYo** [comment]
repull latest and try now

**Comment by jpalenz77** [comment]
YES; working now!! this bot is great, thanks so much

**Comment by StackTraceYo** [comment]
#27

**Comment by StackTraceYo** [comment]
> YES; working now!! this bot is great, thanks so much

cool enjoy.
