### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by lediszep** [StackTraceYo/plex-bot#36]
I keep getting this error when starting the container, any idea why?

``[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE da401d64-be58-4480-a240-aeb1281a11ea java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by StackTraceYo** [comment]
Can you show more of the error log?

**Comment by lediszep** [comment]
Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 37f90cee-f1a1-4f62-b4c5-2b48080762f8 DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 37f90cee-f1a1-4f62-b4c5-2b48080762f8 java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 36b2c70d-bec3-4b20-b1ad-8d84292e560a DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 36b2c70d-bec3-4b20-b1ad-8d84292e560a java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST eef9bbed-ce9b-4aa8-bb16-ad2f1ed8d902 DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE eef9bbed-ce9b-4aa8-bb16-ad2f1ed8d902 java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST da401d64-be58-4480-a240-aeb1281a11ea DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE da401d64-be58-4480-a240-aeb1281a11ea java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST a0d28987-def3-480d-98b7-ae9138c713aa DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE a0d28987-def3-480d-98b7-ae9138c713aa java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST a8968fba-1a8a-42fb-9fb5-4980d57a3746 DeleteWebhook
[error, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE a8968fba-1a8a-42fb-9fb5-4980d57a3746 java.lang.RuntimeException: Error 404 on request

Exception in thread "main" java.lang.RuntimeException: Error 404 on request

at com.bot4s.telegram.clients.ScalajHttpClient.$anonfun$sendRequest$13(ScalajHttpClient.scala:107)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by StackTraceYo** [comment]
Does it happen directly on start? Or once you try and do a command?

**Comment by lediszep** [comment]
Yes when I start the container. I'm running it in unraid.

**Comment by StackTraceYo** [comment]
What's your env file look like.

**Comment by lediszep** [comment]
OMBI_HOST=http://192.168.0.17:3579
OMBI_KEY=87xxxxx
OMBI_BOT_TOKEN=000:AAA
OMBI_BOT_NAME=Nameofbot
BOT_CHAT_ID=-000

**Comment by StackTraceYo** [comment]
and this is the latest image?

**Comment by lediszep** [comment]
Yes latest image, seems to be working now! Not sure what happened. Thanks

**Comment by StackTraceYo** [comment]
404 from the telegram service is kinda out of my hands. Maybe it was down for a bit - that was the background polling that was failing

**Comment by StackTraceYo** [comment]
did you figure out the auth stuff?

**Comment by lediszep** [comment]
Yes got the auth working

**Comment by StackTraceYo** [comment]
cool enjoy.

**Comment by lediszep** [comment]
I can't seem to make myself admin even though I have my user ID filled in.

**Comment by StackTraceYo** [comment]
You are using the right env variable for the admin id? And made sure that it's your user Id in there. There's a bot you can use.

**Comment by lediszep** [comment]
I used @userinfobot and have the following:

OMBI_HOST=http://192.168.0.17:3579
OMBI_KEY=87xxxxx
OMBI_BOT_TOKEN=000:AAA
OMBI_BOT_NAME=Nameofbot
BOT_ADMIN=444444444
BOT_CHAT_ID=-000

I get back 'You are not authorized to make this request'

[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 66f5df5e-0130-4ed1-b748-943220e21033 GetUpdates(None,None,Some(30),None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 66f5df5e-0130-4ed1-b748-943220e21033 List(Update(14725415,Some(Message(2461,Some(User(413621433,false,Shaun,None,Some(Shaunofthadead),Some(en))),1595476740,Chat(413621433,Private,None,Some(Shaunofthadead),Some(Shaun),None,None,None,None,None,None,None,None,None),None,None,None,None,None,None,None,None,None,Some(/register),Some(List(MessageEntity(BotCommand,0,9,None,None))),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)),None,None,None,None,None,None,None,None,None))
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 8858bb02-4088-40f7-a853-4dd8c48469e6 GetUpdates(Some(14725416),None,Some(30),None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST f675ffca-40bb-4e31-be5f-55ef638a5d79 SendMessage(Chat(413621433),You are not authorized to make this request,Some(Markdown),None,None,None,None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE f675ffca-40bb-4e31-be5f-55ef638a5d79 Message(2462,Some(User(518696361,true,GERTY,None,Some(MoonlightmediaBot),None)),1595476740,Chat(413621433,Private,None,Some(Shaunofthadead),Some(Shaun),None,None,None,None,None,None,None,None,None),None,None,None,None,None,None,None,None,None,Some(You are not authorized to make this request),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 16e3a965-a88c-4e9d-b5fd-18b78afda377 DeleteMessage(Chat(413621433),2462)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 16e3a965-a88c-4e9d-b5fd-18b78afda377 true
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 8858bb02-4088-40f7-a853-4dd8c48469e6 List()
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST de900d0f-0f37-4532-95f4-a8638b8ce7b0 GetUpdates(Some(14725416),None,Some(30),None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 8858bb02-4088-40f7-a853-4dd8c48469e6 List()
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST de900d0f-0f37-4532-95f4-a8638b8ce7b0 GetUpdates(Some(14725416),None,Some(30),None)

**Comment by StackTraceYo** [comment]
What command are you running? You're automatically the admin if you put the admin_id. Does it Show error when you do /authon

**Comment by lediszep** [comment]
I'm running /register
If I use the /authon command I get: 'Authorization support is not available without an admin'

**Comment by StackTraceYo** [comment]
so either it didnt get your admin variable or theres a bug. can you run

`docker exec <container_name> env`

and make sure that BOT_ADMIN is there

**Comment by lediszep** [comment]
It's working now, seems like it wasn't updating the bot.env file for some reason.
