### ISSUE TITLE
No response to /search with new Ombi v4

### ISSUE THREAD

**Issue by guisua** [StackTraceYo/plex-bot#39]
### The problem
- My bot doesn't respond to searches when configured with Ombi v4.

### Chronology
- Everything was working under v3.
- I moved to the new Plex Movie agent which is not supported by v3 (content doesn't match IMDB IDs) so I tried Ombi v4. 
- I have two docker containers, one for v3 and one for v4. Both run on the same host (IP and port). Of course I don't run both at the same time.
- The `bot.env` is exactly the same (same file), I only update the Ombi token accordingly.

Here are the responses from the bot for different scenarios:

#### v3 with correct Ombi token
```
Searching Movies and TV
```

#### v3 with incorrect token
```
Searching Movies and TV
No Available Results
No Search Results
No Available Results
No Search Results
```

#### v4 with/without correct token
```
Searching Movies and TV
```

**Comment by daurpam** [comment]
I've only tested with ombi v4, and got the same results as @guisua

**Comment by StackTraceYo** [comment]
did you try the new docker for v4? @guisua @daurpam

**Comment by guisua** [comment]
@StackTraceYo yes but I still get no response. I have also tested the apiKey against the Ombi host directly and it is valid

**Comment by StackTraceYo** [comment]
can you print me some logs

**Comment by StackTraceYo** [comment]
I just pushed a new version of the 2.2-OMBI-V4 image with better logging. please try it and let me know what you see.

**Comment by StackTraceYo** [comment]
also - simple mistake ive made in the past is misconfiguring the hostnames- 

make sure the OMBI_HOST has the right base url (found  in Ombi Configuration on the UI).

**Comment by guisua** [comment]
I just pulled the image now and here are the logs. I have redacted a few fields. 

```
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST a36b22fc-da5c-4e8d-8fc8-7ab7db73e7f1 GetUpdates(None,None,Some(30),None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE a36b22fc-da5c-4e8d-8fc8-7ab7db73e7f1 List(Update(<ID>,Some(Message(3866,Some(User(<ID>,false,<FIRSTNAME>,Some(<LASTNAME>),Some(<USERNAME>),Some(en))),<ID>,Chat(<ID>,Private,None,Some(<USERNAME>),Some(<FIRSTNAME>),Some(<LASTNAME>),None,None,None,None,None,None,None,None),None,None,None,None,None,None,None,None,None,Some(/search friends),Some(List(MessageEntity(BotCommand,0,7,None,None))),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)),None,None,None,None,None,None,None,None,None))
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST a5175d7d-f147-4d7c-9da0-968d73527c2f GetUpdates(Some(<ID>),None,Some(30),None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] REQUEST 1215a73d-fc35-4223-a4b8-01265b5fc221 SendMessage(Chat(<ID>),*Searching Movies and TV*,Some(Markdown),None,Some(true),None,None)
[trace, com.bot4s.telegram.clients.ScalajHttpClient] RESPONSE 1215a73d-fc35-4223-a4b8-01265b5fc221 Message(3867,Some(User(<ID>,true,Plexy,None,Some(guisua_ombibot),None)),<ID>,Chat(<ID>,Private,None,Some(<USERNAME>),Some(<FIRSTNAME>),Some(<LASTNAME>),None,None,None,None,None,None,None,None),None,None,None,None,None,None,None,None,None,Some(Searching Movies and TV),Some(List(MessageEntity(Bold,0,23,None,None))),None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None)
```

**Comment by StackTraceYo** [comment]
is that all? if you pulled the new request and you were getting an error we should be seeing the error being logged. are you positive its using the new image?

**Comment by guisua** [comment]
Yes, I just deleted both the container and the image and pulled the image `:2.2-OMBI-V4` from the hub again for good measure. Those are all the logs I get.

**Comment by StackTraceYo** [comment]
ok im adding some more logging will push a new image shortly.

**Comment by StackTraceYo** [comment]
new image pushed

**Comment by guisua** [comment]
I don't understand it. I just deleted everything again and pulled the image from the hub and still don't see any more logs than before and still no response to the search other than the "Searching" reply (so the Telegram token must be configured correctly).

What are the new logs supposed to look like?

**Comment by PolliSoft** [comment]
I see the same issue, non-Docker version.
https://pastebin.com/wUY3hWa7
![bild](https://user-images.githubusercontent.com/563252/99438821-a177cd80-2914-11eb-8c50-beb2c8060e7c.png)

**Comment by PolliSoft** [comment]
Could this be due to an error in Ombi v4?
I get the following error when browsing to http://localhost:5000/swagger/index.html.
![bild](https://user-images.githubusercontent.com/563252/99441443-2a443880-2918-11eb-9c24-87cf57db97d7.png)
```
2020-11-17 20:56:21.688 +01:00 [Error] Something bad happened, ErrorMiddleware caught this

System.NotSupportedException: Conflicting method/path combination "POST api/v1/Radarr/tags" for actions - Ombi.Controllers.V1.External.RadarrController.GetTags (Ombi),Ombi.Controllers.V1.External.RadarrController.GetTags (Ombi). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)

   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 56

   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Comment by Casuallynoted** [comment]
My Ombi V4 bot seems to no longer respond at all when commands go in. It definitely prints them, but it outputs a bunch of "none,none,none" in the terminal and nothing on Telegram at all.

Stuff like this:
![Test](https://user-images.githubusercontent.com/6272557/100189856-25086000-2ebb-11eb-8723-be04a83abc78.png)

Not sure if this is the same issue or not though.

**Comment by PolliSoft** [comment]
After updating Ombi to 4.0.728.0, it now works for me.
http://localhost:5000/swagger/index.html also works now.
